version: "3"

services:
  db:
    image: bitnami/postgresql
    volumes:
      - db_data:/bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=ps123
      - POSTGRESQL_DATABASE=db

volumes:
  db_data:
