# @name get-prompts
GET http://localhost:3334/prompts/list

### 

# @name /videos/upload
POST http://localhost:3334/videos/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/npeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 

# @name /videos/{video-id}/transcription
POST http://localhost:3334/videos/d0808f72-8951-4e7c-a578-2138a608baf5/transcription
Content-Type: application/json

{
    "prompt": "prompt example"
}

### 

# @name /ai/completion
POST http://localhost:3334/ai/completion
Content-Type: application/json

{
    "videoId": "d0808f72-8951-4e7c-a578-2138a608baf5",
    "prompt": "Gere um resumo sucinto da transcrição do video informado a seguir: '''{transcription}'''",
    "temperature": 0.5
}
